spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  http:
    encoding:
      charset: UTF-8
server:
  port: ${PORT:8090}
  ssl:
    enabled: true
    key-store: classpath:springapp.jks
    key-store-password: thanhnd
    key-alias: springapp